### ISSUE TITLE
[QUESTION] Which Package?

### ISSUE THREAD

**Issue by noxify** [pingpong-labs/sky#1]
Hi,

is it better to use your "SKY" package in the future or your standalone packages?

Thanks!

**Comment by gravitano** [comment]
Hi,

It depends on your needs. If your application requires all or most of the components of the "sky" package, then use the "sky". But if only partial, it is better to use a package that you just need.

I made this because it would be easier for me to maintenance for every my packages.

**Comment by noxify** [comment]
Hi,

thanks :) currently I'm using only modules and menu - so I think, the complete package is a bit overkill in the current project - but maybe in future projects..

Thanks!
