### ISSUE TITLE
Folder "Filter" is now called "middleware"

### ISSUE THREAD

**Issue by ghost** [pingpong-labs/sky#2]
Please correct this from title.

In the final laraval version the folder "Filter" is now called "middleware" 

See original app directory.

additionally the folders "Services", "Commands" and "Events" is missing and which sense have the folders "Repositories", "Resources" and "Entities" ?

Thanks for reading.

**Comment by gravitano** [comment]
I know that. For now you can add additional folders in the configuration file of modules package. If you publish the package's config you can modify the file in config/modules.php (in Laravel 5). You can add new folders as you want in `paths.generator` key. Something like : 

``` php
//...
'generator' => [
           'assets' => 'Assets',
            'config' => 'Config',
            'command' => 'Console',
            'migration' => 'Database/Migrations',
            'model' => 'Entities',
            'repository' => 'Repositories',
            'seeder' => 'Database/Seeders',
            'controller' => 'Http/Controllers',
            'filter' => 'Http/Middleware',
            'request' => 'Http/Requests',
            'provider' => 'Providers',
            'lang' => 'Resources/lang',
            'views' => 'Resources/views',
            'services' => 'Services',
            'commands' => 'Commands',
            'events => 'Events',
]
//...
```

Maybe I will make that as default for next commit :)

**Comment by gravitano** [comment]
I've replaced `Filters` with `Middleware`.
