### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/sky#3]
> Sky is an extra Laravel packages.
> Isn't really correct English. 'an' = singular , 'packages' = plural.

Might be:

> Sky are extra Laravel Packages

Or:

> Sky is an extra Laravel package.

Same here

> Here is some of most polular package which is a part of SKY package.

Should be `Here are some of the most popular packages...`

**Comment by gravitano** [comment]
Hi, thank you for telling me. I'll fix it soon :)
