### ISSUE TITLE
Documentation download

### ISSUE THREAD

**Issue by MiguelLink2Lux** [pingpong-labs/sky#8]
the documentation website is down. Can i donwload the documentation in other site?

**Comment by edyrkaj** [comment]
Website is down. Any other method to retrieve documentation? 
Thank you

**Comment by senycorp** [comment]
Same here. Please make documentation accessible in any possible form. That would be greate. Actually i am checking the code all the time. It feels like studying your great code style instead of development :).

By the way - Many thanks for your wonderful job. You made every day wonderfull :+1:

**Comment by gravitano** [comment]
Hey guys, offline documentation is available here https://github.com/pingpong-labs/docs. I am sorry for the website.
